
import { NameOfAllah } from '../types';

const getAudioUrl = (slug: string) => `https://islamicapi.com/audio/asma-ul-husna/${slug}.mp3`;

// Data Structure: 
// [id, arabic, audio_slug, tr_en, trans_en, mean_en, tr_bn, trans_bn, mean_bn]
const rawData: Array<[number, string, string, string, string, string, string, string, string]> = [
  [1, "الرَّحْمَنُ", "rahman", "Ar-Rahman", "The Beneficent", "He who wills goodness and mercy for all His creatures", "আর-রাহমান", "পরম দয়ালু", "যিনি দুনিয়াতে মুমিন ও কাফির নির্বিশেষে সকলের প্রতি দয়াশীল।"],
  [2, "الرَّحِيمُ", "raheem", "Ar-Raheem", "The Merciful", "He who acts with extreme kindness", "আর-রাহীম", "অতি মেহেরবান", "যিনি পরকালে শুধুমাত্র মুমিনদের প্রতি দয়াশীল হবেন।"],
  [3, "الْمَلِكُ", "malik", "Al-Malik", "The King", "The Sovereign Lord, The One with the complete Dominion", "আল-মালিক", "সর্বকর্তৃত্বময়", "যিনি সর্বভৌধ ক্ষমতার অধিকারী।"],
  [4, "الْقُدُّوسُ", "quddus", "Al-Quddus", "The Most Holy", "The One who is pure from any imperfection", "আল-কুদ্দুস", "অতি পবিত্র", "যিনি সমস্ত অসম্পূর্ণতা থেকে মুক্ত।"],
  [5, "السَّلاَمُ", "salam", "As-Salam", "The Source of Peace", "The One who is free from every imperfection", "আস-সালাম", "শান্তি বিধায়ক", "যিনি শান্তি ও নিরাপত্তার উৎস।"],
  [6, "الْمُؤْمِنُ", "mumin", "Al-Mu'min", "The Guardian of Faith", "The One who witnessed for Himself that no one is God but Him", "আল-মুমিন", "নিরাপত্তা দানকারী", "যিনি সৃষ্টিজগতকে নিরাপত্তা প্রদান করেন।"],
  [7, "الْمُهَيْمِنُ", "muhaymin", "Al-Muhaymin", "The Protector", "The One who witnesses the saying and deeds of His creatures", "আল-মুহাইমিন", "রক্ষনাবেক্ষণকারী", "যিনি সৃষ্টিজগতের রক্ষণাবেক্ষণ ও প্রতিপালন করেন।"],
  [8, "الْعَزِيزُ", "aziz", "Al-Aziz", "The All Mighty", "The Defeater who is not defeated", "আল-আযীয", "মহাপরাক্রমশালী", "যিনি সবার উপর পরাক্রমশালী।"],
  [9, "الْجَبَّارُ", "jabbar", "Al-Jabbar", "The Compeller", "The One that nothing happens in His Dominion except that which He willed", "আল-জাব্বার", "মহাপ্রতাবশালী", "যিনি নিজের ইচ্ছা ও নির্দেশকে সকলের উপর কার্যকর করেন।"],
  [10, "الْمُتَكَبِّرُ", "mutakabbir", "Al-Mutakabbir", "The Supreme", "The One who is clear from the attributes of the creatures", "আল-মুতাকাব্বির", "অহংকারের ন্যায্য অধিকারী", "যিনি সমস্ত সৃষ্টিজগতের তুলনায় শ্রেষ্ঠ।"],
  [11, "الْخَالِقُ", "khaliq", "Al-Khaliq", "The Creator", "The One who brings everything from non-existence to existence", "আল-খালিক্ব", "সৃষ্টিকর্তা", "যিনি অস্তিত্বহীন থেকে সবকিছু সৃষ্টি করেছেন।"],
  [12, "الْبَارِئُ", "bari", "Al-Bari", "The Evolver", "The Maker, The Creator who has the power to turn the entities", "আল-বারী", "সঠিকভাবে সৃষ্টিকারী", "যিনি সৃষ্টির মধ্যে সামঞ্জস্য বিধান করেন।"],
  [13, "الْمُصَوِّرُ", "musawwir", "Al-Musawwir", "The Fashioner", "The One who forms His creatures in different pictures", "আল-মুসাউবির", "আকৃতিদানকারী", "যিনি প্রতিটি সৃষ্টির স্বতন্ত্র আকৃতি ও রূপ দান করেন।"],
  [14, "الْغَفَّارُ", "ghaffar", "Al-Ghaffar", "The Great Forgiver", "The Forgiver, The One who forgives the sins of His slaves time and time again", "আল-গাফফার", "পরম ক্ষমাশীল", "যিনি বারবার বান্দার পাপ ক্ষমা করেন।"],
  [15, "الْقَهَّارُ", "qahhar", "Al-Qahhar", "The Subduer", "The Dominant, The One who has the perfect Power and is not unable over anything", "আল-কাহহার", "কঠোর", "যিনি অবাধ্যদের পরাভূত করতে সক্ষম।"],
  [16, "الْوَهَّابُ", "wahhab", "Al-Wahhab", "The Bestower", "The One who is Generous in giving plenty without any return", "আল-ওয়াহহাব", "সবকিছু দানকারী", "যিনি বিনিময় ছাড়াই সবকিছু দান করেন।"],
  [17, "الرَّزَّاقُ", "razzaq", "Ar-Razzaq", "The Provider", "The Sustainer, The One who provides sustenance/provision", "আর-রাজ্জাক", "রিজিকদাতা", "যিনি সকল সৃষ্টির রিজিকের ব্যবস্থা করেন।"],
  [18, "الْفَتَّاحُ", "fattah", "Al-Fattah", "The Opener", "The Reliever, The Judge, The One who opens for His slaves the closed worldly and religious matters", "আল-ফাত্তাহ", "বিজয়দানকারী", "যিনি রহমত ও বিজয়ের দ্বার উন্মুক্ত করেন।"],
  [19, "الْعَلِيمُ", "alim", "Al-Alim", "The All-Knowing", "The Knowledgeable; The One nothing is absent from His knowledge", "আল-আলিম", "সর্বজ্ঞ", "যিনি সবকিছু জানেন, গোপন ও প্রকাশ্য।"],
  [20, "الْقَابِضُ", "qabid", "Al-Qabid", "The Constrictor", "The Constrictor, The Withholder, The One who constricts the sustenance", "আল-কাবিদ", "সংকুচিতকারী", "যিনি রিজিক ও জীবন সংকুচিত করেন।"],
  [21, "الْبَاسِطُ", "basit", "Al-Basit", "The Expander", "The Englarger, The One who expands and widens", "আল-বাসিত", "প্রশস্তকারী", "যিনি রিজিক ও হায়াত প্রশস্ত করেন।"],
  [22, "الْخَافِضُ", "khafid", "Al-Khafid", "The Abaser", "The One who lowers whoever He willed by His Destruction", "আল-খাফিদ", "অবনতকারী", "যিনি অবিশ্বাসীদের অপমানিত ও লাঞ্ছিত করেন।"],
  [23, "الرَّافِعُ", "rafi", "Ar-Rafi", "The Exalter", "The One who raises whoever He willed by His Endowment", "আর-রাফি", "উন্নতকারী", "যিনি বিশ্বাসীদের মর্যাদা উন্নত করেন।"],
  [24, "الْمُعِزُّ", "muizz", "Al-Muizz", "The Honorer", "He gives esteem to whoever He willed, hence there is no one to degrade Him", "আল-মুইজ্জ", "সম্মানদানকারী", "যিনি যাকে ইচ্ছা সম্মান দান করেন।"],
  [25, "الْمُذِلُّ", "mudhill", "Al-Mudhill", "The Dishonorer", "He degrades whoever He willed, hence there is no one to give Him esteem", "আল-মুযিল্ল", "অপমানকারী", "যিনি যাকে ইচ্ছা অপমানিত করেন।"],
  [26, "السَّمِيعُ", "sami", "As-Sami", "The All-Hearing", "The One who hears all things that are heard by His Eternal Hearing", "আস-সামি", "সর্বশ্রোতা", "যিনি সবকিছু শোনেন।"],
  [27, "الْبَصِيرُ", "basir", "Al-Basir", "The All-Seeing", "The One who sees all things that are seen by His Eternal Seeing", "আল-বাসির", "সর্বদ্রষ্টা", "যিনি সবকিছু দেখেন।"],
  [28, "الْحَكَمُ", "hakam", "Al-Hakam", "The Judge", "He is the Ruler and His judgment is His Word", "আল-হাকাম", "বিচারক", "যিনি চূড়ান্ত ফয়সালাকারী।"],
  [29, "الْعَدْلُ", "adl", "Al-Adl", "The Just", "The One who is entitled to do what He does", "আল-আদল", "ন্যায়বিচারক", "যিনি পরিপূর্ণ ন্যায়বিচারক।"],
  [30, "اللَّطِيفُ", "latif", "Al-Latif", "The Subtle One", "The One who is kind to His slaves and endows upon them", "আল-লতিফ", "সূক্ষ্মদর্শী", "যিনি বান্দার প্রতি অতি মেহেরবান ও সূক্ষ্ম বিষয়ের খবর রাখেন।"],
  [31, "الْخَبِيرُ", "khabir", "Al-Khabir", "The All-Aware", "The One who knows the truth of things", "আল-খাবির", "মহা সংবাদরক্ষক", "যিনি সবকিছুর গোপন খবর রাখেন।"],
  [32, "الْحَلِيمُ", "halim", "Al-Halim", "The Forbearing", "The One who delays the punishment for those who deserve it", "আল-হালিম", "সহিষ্ণু", "যিনি ধৈর্যশীল ও সহনশীল।"],
  [33, "الْعَظِيمُ", "azim", "Al-Azim", "The Magnificent", "The One deserving the attributes of Exaltment, Glory, Extolment, and Purity", "আল-আজিম", "মহান", "যিনি সর্বোচ্চ মর্যাদার অধিকারী।"],
  [34, "الْغَفُورُ", "ghafur", "Al-Ghafur", "The Forgiver", "The One who forgives a lot", "আল-গফুর", "ক্ষমাকারী", "যিনি গুনাহ মাফ করেন।"],
  [35, "الشَّكُورُ", "shakur", "Ash-Shakur", "The Appreciative", "The One who gives a lot of reward for a little obedience", "আশ-শাকুর", "গুণগ্রাহী", "যিনি অল্প আমলে বেশি প্রতিদান দেন।"],
  [36, "الْعَلِيُّ", "ali", "Al-Ali", "The Most High", "The One who is clear from the attributes of the creatures", "আল-আলি", "উচ্চমর্যাদাশীল", "যিনি সর্বোচ্চ আসনের অধিকারী।"],
  [37, "الْكَبِيرُ", "kabir", "Al-Kabir", "The Most Great", "The One who is greater than everything in status", "আল-কাবির", "সুমহান", "যিনি সবার চেয়ে বড়।"],
  [38, "الْحَفِيظُ", "hafiz", "Al-Hafiz", "The Preserver", "The One who protects whatever and whoever He willed to protect", "আল-হাফিজ", "মহারক্ষক", "যিনি সবকিছু সংরক্ষণ করেন।"],
  [39, "الْمُقِيتُ", "muqit", "Al-Muqit", "The Maintainer", "The Sustainer, The One who has the Power", "আল-মুকিত", "আহারদাতা", "যিনি সকলের আহার ও শক্তি যোগান।"],
  [40, "الْحَسِيبُ", "hasib", "Al-Hasib", "The Reckoner", "The One who gives the satisfaction", "আল-হাসিব", "হিসাব গ্রহণকারী", "যিনি সবার হিসাব নিবেন।"],
  [41, "الْجَلِيلُ", "jalil", "Al-Jalil", "The Sublime One", "The One who is attributed with greatness of Power and Glory of status", "আল-জলিল", "মহিমাম্বিত", "যিনি পরম মর্যাদাবান।"],
  [42, "الْكَرِيمُ", "karim", "Al-Karim", "The Generous One", "The One who is clear from abasement", "আল-কারিম", "মহান দাতা", "যিনি অত্যন্ত সম্মানিত ও দয়ালু।"],
  [43, "الرَّقِيبُ", "raqib", "Ar-Raqib", "The Watchful", "The One that nothing is absent from Him", "আর-রাকিব", "তত্ত্বাবধায়ক", "যিনি সবসময় সবকিছু পর্যবেক্ষণ করেন।"],
  [44, "الْمُجِيبُ", "mujib", "Al-Mujib", "The Responsive", "The One who answers the one in need if he asks Him", "আল-মুজিব", "কবুলকারী", "যিনি দোয়া কবুল করেন।"],
  [45, "الْوَاسِعُ", "wasi", "Al-Wasi", "The All-Encompassing", "The Knowledgeable", "আল-ওয়াসি", "প্রশস্ত", "যিনি জ্ঞান ও রহমতে সবকিছু পরিবেষ্টন করে আছেন।"],
  [46, "الْحَكِيمُ", "hakim", "Al-Hakim", "The Wise", "The One who is correct in His acts", "আল-হাকিম", "প্রজ্ঞাময়", "যিনি মহাজ্ঞানী ও প্রজ্ঞাবান।"],
  [47, "الْوَدُودُ", "wadud", "Al-Wadud", "The Loving", "The One who loves His believing slaves", "আল-ওয়াদুদ", "প্রেমময়", "যিনি বান্দাদের ভালোবাসেন।"],
  [48, "الْمَجِيدُ", "majid", "Al-Majid", "The Glorious", "The One who is with perfect Power, High Status, Compassion, Generosity and Kindness", "আল-মাজিদ", "গৌরবময়", "যিনি মহিমান্বিত।"],
  [49, "الْبَاعِثُ", "baith", "Al-Baith", "The Resurrecter", "The One who resurrects His slaves after death", "আল-বাইল", "পুনরুত্থানকারী", "যিনি মৃত্যুর পর পুনরায় জীবন দান করবেন।"],
  [50, "الشَّهِيدُ", "shahid", "Ash-Shahid", "The Witness", "The One who nothing is absent from Him", "আশ-শাহিদ", "সাক্ষী", "যিনি সবকিছুর সাক্ষী।"],
  [51, "الْحَقُّ", "haqq", "Al-Haqq", "The Truth", "The One who truly exists", "আল-হক", "সত্য", "যিনি পরম সত্য।"],
  [52, "الْوَكِيلُ", "wakil", "Al-Wakil", "The Trustee", "The One who gives the satisfaction and is relied upon", "আল-ওয়াকিল", "কার্যনির্বাহক", "যিনি ভরসাস্থল ও কর্মবিধায়ক।"],
  [53, "الْقَوِيُّ", "qawiyy", "Al-Qawiyy", "The Most Strong", "The One with the complete Power", "আল-কাবি", "শক্তিশালী", "যিনি মহাবলবান।"],
  [54, "الْمَتِينُ", "matin", "Al-Matin", "The Firm One", "The One with extreme Power which is un-interrupted", "আল-মতিন", "দৃঢ়", "যিনি অত্যন্ত সুদৃঢ়।"],
  [55, "الْوَلِيُّ", "wali", "Al-Wali", "The Protecting Friend", "The Supporter", "আল-ওয়ালি", "অভিভাবক", "যিনি মুমিনদের বন্ধু ও সাহায্যকারী।"],
  [56, "الْحَمِيدُ", "hamid", "Al-Hamid", "The Praiseworthy", "The praised One who deserves to be praised", "আল-হামিদ", "প্রশংসিত", "যিনি সকল প্রশংসার যোগ্য।"],
  [57, "الْمُحْصِي", "muhsi", "Al-Muhsi", "The Reckoner", "The One who the count of things are known to him", "আল-মুহসি", "হিসাবরক্ষণকারী", "যিনি সবকিছুর হিসাব রাখেন।"],
  [58, "الْمُبْدِئُ", "mubdi", "Al-Mubdi", "The Originator", "The One who started the human being", "আল-মুবদি", "আদি স্রষ্টা", "যিনি প্রথমবার সৃষ্টি করেন।"],
  [59, "الْمُعِيدُ", "muid", "Al-Muid", "The Restorer", "The One who brings back the creatures after death", "আল-মুঈদ", "পুনঃসৃষ্টিকারী", "যিনি পুনরায় সৃষ্টি করবেন।"],
  [60, "الْمُحْيِي", "muhyi", "Al-Muhyi", "The Giver of Life", "The One who took out a living human from semen", "আল-মুহিম", "জীবনদানকারী", "যিনি জীবন দান করেন।"],
  [61, "الْمُمِيتُ", "mumit", "Al-Mumit", "The Creator of Death", "The One who renders the living dead", "আল-মুমিত", "মৃত্যুদাতা", "যিনি মৃত্যু দান করেন।"],
  [62, "الْحَيُّ", "hayy", "Al-Hayy", "The Alive", "The One attributed with a life that is unlike our life", "আল-হাইয়্যুল", "চিরঞ্জীব", "যিনি চিরঞ্জীব।"],
  [63, "الْقَيُّومُ", "qayyum", "Al-Qayyum", "The Self-Subsisting", "The One who remains and does not end", "আল-কাইয়ুম", "চিরস্থায়ী", "যিনি নিজে বিদ্যমান এবং সবকিছু ধারণ করেন।"],
  [64, "الْوَاجِدُ", "wajid", "Al-Wajid", "The Finder", "The Rich who is never poor", "আল-ওয়াজিদ", "আবিষ্কারক", "যিনি সবকিছু পান বা সবকিছুর মালিক।"],
  [65, "الْمَاجِدُ", "majid_2", "Al-Majid", "The Noble", "The One who is Noble", "আল-মাজিদ", "মহিমান্বিত", "যিনি মহানুভব।"],
  [66, "الْوَاحِدُ", "wahid", "Al-Wahid", "The Unique", "The One without a partner", "আল-ওয়াহিদ", "একক", "যিনি এক ও অদ্বিতীয়।"],
  [67, "الْأَحَد", "ahad", "Al-Ahad", "The One", "The Only One", "আল-আহাদ", "এক", "যিনি এক সত্তা।"],
  [68, "الصَّمَدُ", "samad", "As-Samad", "The Eternal", "The Master who is relied upon in matters and reverted to in ones needs", "আস-সামাদ", "অমুখাপেক্ষী", "যিনি কারো মুখাপেক্ষী নন, সবাই তাঁর মুখাপেক্ষী।"],
  [69, "الْقَادِرُ", "qadir", "Al-Qadir", "The Able", "The One attributed with Power", "আল-কাদির", "ক্ষমতাবান", "যিনি সবকিছুর উপর ক্ষমতাবান।"],
  [70, "الْمُقْتَدِرُ", "muqtadir", "Al-Muqtadir", "The Powerful", "The One with the perfect Power", "আল-মুকতাদির", "প্রভাবশালী", "যিনি প্রবল ক্ষমতার অধিকারী।"],
  [71, "الْمُقَدِّمُ", "muqaddim", "Al-Muqaddim", "The Expediter", "The One who puts things in their right places", "আল-মুকাদ্দিম", "অগ্রবর্তীকারী", "যিনি যাকে ইচ্ছা অগ্রবর্তী করেন।"],
  [72, "الْمُؤَخِّرُ", "muakhkhir", "Al-Muakhkhir", "The Delayer", "The One who delays what He wants", "আল-মুয়াক্ষির", "পিছিয়ে দেনেওয়ালা", "যিনি যাকে ইচ্ছা পশ্চাদবর্তী করেন।"],
  [73, "الْأَوَّلُ", "awwal", "Al-Awwal", "The First", "The One whose Existence is without a beginning", "আল-আউয়াল", "অনাদি", "যিনি সবার আগে।"],
  [74, "الْآخِرُ", "akhir", "Al-Akhir", "The Last", "The One whose Existence is without an end", "আল-আখির", "অনন্ত", "যিনি সবার শেষে।"],
  [75, "الظَّاهِرُ", "zahir", "Az-Zahir", "The Manifest", "The One that nothing is above Him and nothing is underneath Him", "আজ-জাহির", "প্রকাশ্য", "যিনি প্রকাশ্য।"],
  [76, "الْبَاطِنُ", "batin", "Al-Batin", "The Hidden", "The One that nothing is above Him and nothing is underneath Him", "আল-বাতিন", "গোপন", "যিনি গোপন।"],
  [77, "الْوَالِي", "wali_2", "Al-Wali", "The Governor", "The One who owns things and manages them", "আল-ওয়ালি", "কর্তা", "যিনি সমস্ত কিছুর অভিভাবক।"],
  [78, "الْمُتَعَالِي", "mutaali", "Al-Muta'ali", "The Most Exalted", "The One who is clear from the attributes of the creation", "আল-মুতাআলি", "সর্বোচ্চ", "যিনি সৃষ্টির গুণাবলী থেকে পবিত্র।"],
  [79, "الْبَرُّ", "barr", "Al-Barr", "The Source of Goodness", "The One who is kind to His creatures", "আল-বার্", "কল্যাণময়", "যিনি পরম দয়ালু ও অনুগ্রহকারী।"],
  [80, "التَّوَّابُ", "tawwab", "At-Tawwab", "The Acceptor of Repentance", "The One who grants repentance", "আত-তাওয়াব", "তওবা কবুলকারী", "যিনি তওবা কবুল করেন।"],
  [81, "الْمُنْتَقِمُ", "muntaqim", "Al-Muntaqim", "The Avenger", "The One who victoriously prevails over His enemies and punishes them for their sins", "আল-মুনতাকিম", "প্রতিশোধ গ্রহণকারী", "যিনি অপরাধীদের শাস্তি দেন।"],
  [82, "الْعَفُوُّ", "afu", "Al-Afu", "The Pardoner", "The One with wide forgiveness", "আল-আফুন", "ক্ষমাকারী", "যিনি পাপ মোচন করেন।"],
  [83, "الرَّءُوفُ", "rauf", "Ar-Rauf", "The Compassionate", "The One with extreme Mercy", "আর-রাউফ", "স্নেহশীল", "যিনি অত্যন্ত স্নেহশীল।"],
  [84, "مَالِكُ الْمُلْكِ", "malikulmulk", "Malik-ul-Mulk", "The Eternal Owner of Sovereignty", "The One who controls the Dominion and gives dominion to whoever He willed", "মালিকুল মুলক", "সার্বভৌম ক্ষমতার অধিকারী", "যিনি সমগ্র জগতের মালিক।"],
  [85, "ذُو الْجَلالِ وَالْإِكْرَامِ", "dhuljalaliwalikram", "Dhul-Jalali-Wal-Ikram", "The Lord of Majesty and Bounty", "The One who deserves to be Exalted and not denied", "জুল জালালি ওয়াল ইকরাম", "মহিমাম্বিত ও দয়ার আধার", "যিনি মহত্ত্ব ও সম্মানের অধিকারী।"],
  [86, "الْمُقْسِطُ", "muqsit", "Al-Muqsit", "The Equitable", "The One who is Just in His judgment", "আল-মুকসিত", "ন্যায়পরায়ণ", "যিনি ন্যায়বিচারক।"],
  [87, "الْجَامِعُ", "jami", "Al-Jami", "The Gatherer", "The One who gathers the creatures on a day", "আল-জামি", "একত্রকারী", "যিনি কিয়ামতের দিন সবাইকে একত্রিত করবেন।"],
  [88, "الْغَنِيُّ", "ghani", "Al-Ghani", "The Self-Sufficient", "The One who does not need the creation", "আল-গনি", "ধনাঢ্য", "যিনি স্বয়ংসম্পূর্ণ।"],
  [89, "الْمُغْنِي", "mughni", "Al-Mughni", "The Enricher", "The One who satisfies the necessities of the creatures", "আল-মুগনি", "অভাবমোচনকারী", "যিনি অভাব মুক্ত করেন।"],
  [90, "الْمَانِعُ", "mani", "Al-Mani", "The Preventer", "The Supporter who protects and gives victory to His pious believers", "আল-মানি", "প্রতিরোধকারী", "যিনি অকল্যাণ রোধ করেন।"],
  [91, "الضَّارُّ", "darr", "Ad-Darr", "The Distresser", "The One who makes harm reach to whoever He willed", "আদ-দার", "ক্ষতিকারী", "যিনি ক্ষতি করার ক্ষমতার মালিক।"],
  [92, "النَّافِعُ", "nafi", "An-Nafi", "The Propitious", "The One who gives benefits to whoever He willed", "আন-নাফি", "উপকারকারী", "যিনি উপকার করার ক্ষমতার মালিক।"],
  [93, "النُّورُ", "nur", "An-Nur", "The Light", "The One who guides", "আন-নূর", "জ্যোতি", "যিনি আসমান ও জমিনের আলো।"],
  [94, "الْهَادِي", "hadi", "Al-Hadi", "The Guide", "The One whom with His Guidance His believers were guided", "আল-হাদি", "পথপ্রদর্শক", "যিনি সঠিক পথ দেখান।"],
  [95, "الْبَدِيعُ", "badi", "Al-Badi", "The Incomparable", "The One who created the creation and formed it without any preceding example", "আল- badi", "অতুলনীয়", "যিনি অতুলনীয় স্রষ্টা।"],
  [96, "الْبَاقِي", "baqi", "Al-Baqi", "The Everlasting", "The One that the state of non-existence is impossible for Him", "আল-বাকি", "চিরস্থায়ী", "যিনি অনন্তকাল থাকবেন।"],
  [97, "الْوَارِثُ", "warith", "Al-Warith", "The Supreme Inheritor", "The One who remains after the creation vanishes", "আল-ওয়ারিস", "উত্তরাধিকারী", "যিনি সবকিছুর উত্তরাধিকারী।"],
  [98, "الرَّشِيدُ", "rashid", "Ar-Rashid", "The Guide to the Right Path", "The One who guides", "আর-রশিদ", "সঠিক পথ প্রদর্শনকারী", "যিনি সঠিক পথে পরিচালনা করেন।"],
  [99, "الصَّبُورُ", "sabur", "As-Sabur", "The Patient", "The One who does not quickly punish the sinners", "আস-সবুর", "ধৈর্যশীল", "যিনি অত্যন্ত ধৈর্যশীল।"]
];

export const asmaData: Record<'en' | 'bn', NameOfAllah[]> = {
  en: rawData.map(d => ({
    id: d[0],
    arabic: d[1],
    transliteration: d[3],
    translation: d[4],
    meaning: d[5],
    audio: getAudioUrl(d[2])
  })),
  bn: rawData.map(d => ({
    id: d[0],
    arabic: d[1],
    transliteration: d[6],
    translation: d[7],
    meaning: d[8],
    audio: getAudioUrl(d[2])
  }))
};
