

export const hadithChapterTranslations: Record<string, string> = {
  "Revelation": "ওহীর সূচনা",
  "Belief": "ঈমান",
  "Knowledge": "ইলম (জ্ঞান)",
  "Ablutions (Wudu')": "ওজু",
  "Bathing (Ghusl)": "গোসল",
  "Menstrual Periods": "ঋতুস্রাব বা হায়েজ",
  "Rubbing hands and feet with dust (Tayammum)": "তায়াম্মুম",
  "Prayers (Salat)": "সালাত (নামাজ)",
  "Times of the Prayers": "নামাজের সময়সমূহ",
  "Call to Prayers (Adhaan)": "আজান",
  "Friday Prayer": "জুমুআ",
  "Fear Prayer": "ভীভিকালীন নামাজ",
  "The Two Festivals (Eids)": "দুই ঈদ",
  "Witr Prayer": "বিতর নামাজ",
  "Invoking Allah for Rain (Istisqaa)": "ইস্তিসকা (বৃষ্টির জন্য দোয়া)",
  "Eclipses": "সূর্যগ্রহণ ও চন্দ্রগ্রহণ",
  "Prostration During Recital of Qur'an": "তিলাওয়াতের সিজদা",
  "Shortening the Prayers (At-Taqseer)": "কসর নামাজ",
  "Prayer at Night (Tahajjud)": "তাহাজ্জুদ",
  "Virtues of Prayer at Masjid Makkah and Madinah": "মক্কা ও মদিনার মসজিদে নামাজের ফজিলত",
  "Actions while Praying": "নামাজের মধ্যে আমল",
  "Forgetfulness in Prayer": "নামাজে ভুল বা সাহু",
  "Funerals (Al-Janaa'iz)": "জানাজা",
  "Obligatory Charity Tax (Zakat)": "যাকাত",
  "Hajj (Pilgrimage)": "হজ",
  "Hajj": "হজ",
  "`Umrah (Minor pilgrimage)": "ওমরাহ",
  "Pilgrims Prevented from Completing the Pilgrimage": "হজে বাধাগ্রস্ত হওয়া",
  "Penalty of Hunting while on Pilgrimage": "ইহরাম অবস্থায় শিকারের কাফফারা",
  "Virtues of Madinah": "মদিনার ফজিলত",
  "Fasting": "সাওম (রোজা)",
  "Praying at Night in Ramadaan (Taraweeh)": "তারাবীহ নামাজ",
  "Virtues of the Night of Qadr": "লাইলাতুল কদরের ফজিলত",
  "Retiring to a Mosque for Remembrance of Allah (I'tikaf)": "ইতিকাফ",
  "Sales and Trade": "ক্রয়-বিক্রয়",
  "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)": "সালাম বাই (অগ্রিম ক্রয়)",
  "Shuf'a": "শুফ'আ (অগ্রক্রয়াধিকার)",
  "Hiring": "ইজারা (ভাড়া)",
  "Transferance of a Debt from One Person to Another (Al-Hawaala)": "হাওয়ালা (ঋণ স্থানান্তর)",
  "Kafalah": "জামিননামা",
  "Representation, Authorization, Business by Proxy": "ওকালতি (প্রতিনিধিত্ব)",
  "Agriculture": "কৃষি ও চাষাবাদ",
  "Distribution of Water": "পানি বণ্টন",
  "Loans, Payment of Loans, Freezing of Property, Bankruptcy": "ঋণ ও দেউলিয়াত্ব",
  "Khusoomaat": "ঝগড়া-বিবাদ",
  "Lost Things Picked up by Someone (Luqatah)": "লুকাতা (হারানো বস্তু)",
  "Oppressions": "জুলুম ও অত্যাচার",
  "Partnership": "শরিকানা",
  "Mortgaging": "বন্ধক",
  "Manumission of Slaves": "দাস মুক্তি",
  "Makaatib": "মুকাতাব (চুক্তিবদ্ধ দাস)",
  "Gifts": "হিবাহ (উপহার)",
  "Witnesses": "সাক্ষ্য",
  "Peacemaking": "সন্ধি বা মিমাংসা",
  "Conditions": "শর্তাবলী",
  "Wills and Testaments (Wasaayaa)": "ওসিয়ত",
  "Fighting for the Cause of Allah (Jihaad)": "জিহাদ",
  "One-fifth of Booty to the Cause of Allah (Khumus)": "খুমুস (গনিমতের এক-পঞ্চমাংশ)",
  "Jizyah and Mawaada'ah": "জিজিয়া ও সন্ধি",
  "Beginning of Creation": "সৃষ্টির সূচনা",
  "Prophets": "নবীগণের কাহিনী",
  "Virtues and Merits of the Prophet (pbuh) and his Companions": "নবী (সাঃ) ও সাহাবীদের মর্যাদা",
  "Companions of the Prophet": "সাহাবীদের ফজিলত",
  "Merits of the Helpers in Madinah (Ansaar)": "আনসারদের মর্যাদা",
  "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)": "মাগাজী (যুদ্ধসমূহ)",
  "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))": "তাফসীর",
  "Virtues of the Qur'an": "কুরআনের ফজিলত",
  "Wedlock, Marriage (Nikaah)": "বিবাহ (নিকাহ)",
  "Divorce": "তালাক",
  "Supporting the Family": "ভরণ-পোষণ",
  "Food, Meals": "পানাহার",
  "Sacrifice on Occasion of Birth (`Aqiqa)": "আকিকা",
  "Hunting, Slaughtering": "শিকার ও জবেহ",
  "Al-Adha Festival Sacrifice (Adaahi)": "কুরবানী",
  "Drinks": "পানীয়",
  "Patients": "রোগী ও চিকিৎসা",
  "Medicine": "চিকিৎসা",
  "Dress": "পোশাক-পরিচ্ছদ",
  "Good Manners and Form (Al-Adab)": "আদব-কায়দা",
  "Asking Permission": "অনুমতি প্রার্থনা",
  "Invocations": "দোয়া ও মোনাজাত",
  "To make the Heart Tender (Ar-Riqaq)": "রিকাক (হৃদয় গলানো)",
  "Divine Will (Al-Qadar)": "তাকদীর",
  "Oaths and Vows": "কসম ও মান্নত",
  "Expiation for Unfulfilled Oaths": "কসমের কাফফারা",
  "Laws of Inheritance (Al-Faraa'id)": "ফারায়েজ (উত্তরাধিকার)",
  "Limits and Punishments set by Allah (Hudood)": "হুদুদ (দণ্ডবিধি)",
  "Blood Money (Ad-Diyat)": "দিয়াত (রক্তপণ)",
  "Apostates": "মুরতাদ ও বিদ্রোহী",
  "(Statements made under) Coercion": "জোর-জবরদস্তি (ইকরাহ)",
  "Tricks": "কৌশল (হিলা)",
  "Interpretation of Dreams": "স্বপ্নের ব্যাখ্যা",
  "Afflictions and the End of the World": "ফিতনা ও কেয়ামতের আলামত",
  "Judgments (Ahkaam)": "আহকাম (বিচার ব্যবস্থা)",
  "Wishes": "আকাঙ্ক্ষা",
  "Accepting Information Given by a Truthful Person": "খবরে ওয়াহিদ",
  "Holding Fast to the Qur'an and Sunnah": "কুরআন ও সুন্নাহ আঁকড়ে ধরা",
  "Oneness, Uniqueness of Allah (Tawheed)": "তাওহীদ",
  
  // Specific Books (e.g. Muslim)
  "The Book of Mosques and Places of Prayer": "মসজিদ ও নামাজের স্থানসমূহ অধ্যায়",
  "The Book of Prayer - Travellers": "মুসাফিরের নামাজ অধ্যায়",
  "The Book of Prayer - Friday": "জুমুআর নামাজ অধ্যায়",
  "The Book of Prayer - Two Eids": "দুই ঈদের নামাজ অধ্যায়",
  "The Book of Prayer - Rain": "বৃষ্টির নামাজ (ইস্তিসকা) অধ্যায়",
  "The Book of Prayer - Eclipses": "গ্রহণের নামাজ অধ্যায়",
  "The Book of Prayer - Funerals": "জানাজার নামাজ অধ্যায়",
  "The Book of I'tikaf": "ইতিকাফ অধ্যায়",
  "The Book of Suckling": "দুগ্ধপান (রাদা'আহ) অধ্যায়",
  "The Book of Invoking Curses": "অভিশাপ বা লি'আন অধ্যায়",
  "The Book of Emancipating Slaves": "দাস মুক্তি অধ্যায়",
  "The Book of Transactions": "লেনদেন (মুয়ামালাত) অধ্যায়",
  "The Book of Musaqah": "মুসাকাহ (পানি সেচ ও ফসল বন্টন) অধ্যায়",
  "The Book of the Rules of Inheritance": "উত্তরাধিকার আইন (ফারায়েজ) অধ্যায়",
  "The Book of Vows": "মান্নত অধ্যায়",
  "The Book of Oaths": "কসম বা শপথ অধ্যায়",
  "The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)": "কসম, কিসাস ও দিয়াত অধ্যায়",
  "The Book of Legal Punishments": "হুদুদ (দণ্ডবিধি) অধ্যায়",
  "The Book of Judicial Decisions": "বিচার ফয়সালা অধ্যায়",
  "The Book of Lost Property": "হারানো বস্তু (লুকাতা) অধ্যায়",
  "The Book of Jihad and Expeditions": "জিহাদ ও অভিযান অধ্যায়",
  "The Book on Government": "রাষ্ট্র পরিচালনা (ইমারত) অধ্যায়",
  "The Book of Hunting, Slaughter, and what may be Eaten": "শিকার ও জবাই এবং হালাল প্রাণী অধ্যায়",
  "The Book of Sacrifices": "কুরবানী অধ্যায়",
  "The Book of Clothes and Adornment": "পোশাক ও সাজসজ্জা অধ্যায়",
  "The Book of the Merits of the Companions": "সাহাবীদের ফজিলত অধ্যায়",
  "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship": "সদাচরণ, শিষ্টাচার ও আত্মীয়তার সম্পর্ক অধ্যায়",
  "The Book of Destiny": "তাকদীর (ভাগ্য) অধ্যায়",
  "The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness": "জিকির, দোয়া ও তওবা অধ্যায়",
  "The Book of Heart-Melting Traditions": "রিকাক (হৃদয় গলানো) অধ্যায়",
  "The Book of Repentance": "তওবা অধ্যায়",
  "Characteristics of The Hypocrites And Rulings Concerning Them": "মুনাফিকদের বৈশিষ্ট্য ও বিধান",
  "Characteristics of the Day of Judgment, Paradise, and Hell": "কেয়ামত, জান্নাত ও জাহান্নামের বিবরণ",
  "The Book of Paradise, its Description, its Bounties and its Inhabitants": "জান্নাত ও তার নেয়ামতসমূহের বর্ণনা",
  "The Book of Commentary on the Qur'an": "তাফসীর অধ্যায়",

  // Tirmidhi, Nasai and Others
  "The Book on Salat (Prayer)": "সালাত (নামাজ) অধ্যায়",
  "The Book on Al-Witr": "বিতর নামাজ অধ্যায়",
  "The Book on the Day of Friday": "জুমুআ অধ্যায়",
  "The Book on the Two Eids": "দুই ঈদ অধ্যায়",
  "The Book on Traveling": "সফর বা মুসাফির অধ্যায়",
  "The Book on Zakat": "যাকাত অধ্যায়",
  "The Book on Fasting": "সাওম (রোজা) অধ্যায়",
  "The Book on Hajj": "হজ অধ্যায়",
  "The Book on Jana''iz (Funerals)": "জানাজা অধ্যায়",
  "The Book on Marriage": "বিবাহ অধ্যায়",
  "The Book on Suckling": "দুগ্ধপান (রাদা'আহ) অধ্যায়",
  "The Book on Divorce and Li'an": "তালাক ও লি'আন অধ্যায়",
  "The Book on Business": "ব্যবসায়-বাণিজ্য অধ্যায়",
  "The Chapters On Judgements From The Messenger of Allah": "রাসূলুল্লাহ (সাঃ) এর বিচার ফয়সালা অধ্যায়",
  "The Book on Blood Money": "রক্তপণ (দিয়াত) অধ্যায়",
  "The Book on Legal Punishments (Al-Hudud)": "হুদুদ (দণ্ডবিধি) অধ্যায়",
  "The Book on Hunting": "শিকার অধ্যায়",
  "The Book on Sacrifices": "কুরবানী অধ্যায়",
  "The Book on Vows and Oaths": "মান্নত ও কসম অধ্যায়",
  "The Book on Military Expeditions": "যুদ্ধ অভিযান অধ্যায়",
  "The Book on Virtues of Jihad": "জিহাদের ফজিলত অধ্যায়",
  "The Book on Jihad": "জিহাদ অধ্যায়",
  "The Book on Clothing": "পোশাক-পরিচ্ছদ অধ্যায়",
  "The Book on Food": "খাবার অধ্যায়",
  "The Book on Drinks": "পানীয় অধ্যায়",
  "Chapters on Righteousness And Maintaining Good Relations With Relatives": "সদাচরণ ও আত্মীয়তার সম্পর্ক অধ্যায়",
  "Chapters on Medicine": "চিকিৎসা অধ্যায়",
  "Chapters On Inheritance": "উত্তরাধিকার (ফারায়েজ) অধ্যায়",
  "Chapters On Wasaya (Wills and Testament)": "ওসিয়ত অধ্যায়",
  "Chapters On Wala' And Gifts": "ওয়ালা এবং উপহার অধ্যায়",
  "Chapters On Al-Qadar": "তাকদীর অধ্যায়",
  "Chapters On Al-Fitan": "ফিতনা অধ্যায়",
  "Chapters On Dreams": "স্বপ্ন অধ্যায়",
  "Chapters On Witnesses": "সাক্ষ্যদান অধ্যায়",
  "Chapters On Zuhd": "জুহুদ (দুনিয়াবিমুখতা) অধ্যায়",
  "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'": "কেয়ামত, রিকাক ও তাকওয়া অধ্যায়",
  "Chapters on the description of Paradise": "জান্নাতের বিবরণ অধ্যায়",
  "The Book on the Description of Hellfire": "জাহান্নামের বিবরণ অধ্যায়",
  "The Book on Faith": "ঈমান অধ্যায়",
  "Chapters on Knowledge": "ইলম (জ্ঞান) অধ্যায়",
  "Chapters on Seeking Permission": "অনুমতি প্রার্থনা অধ্যায়",
  "Chapters on Manners": "আদব-কায়দা অধ্যায়",
  "Chapters on Parables": "উপমা অধ্যায়",
  "Chapters on The Virtues of the Qur'an": "কুরআনের ফজিলত অধ্যায়",
  "Chapters on Recitation": "কিরাত (তিলাওয়াত) অধ্যায়",
  "Chapters on Tafsir": "তাফসীর অধ্যায়",
  "Chapters on Supplication": "দোয়া অধ্যায়",
  "Chapters on Virtues": "ফজিলত বা মর্যাদা অধ্যায়",

  // Specific Additions for Sunan an-Nasa'i
  "The Book of Water": "পানি অধ্যায়",
  "The Book of Menstruation and Istihadah": "হায়েজ ও ইস্তিহাজা অধ্যায়",
  "The Book of Ghusl and Tayammum": "গোসল ও তায়াম্মুম অধ্যায়",
  "The Book of Salah": "সালাত (নামাজ) অধ্যায়",
  "The Book of the Times (of Prayer)": "নামাজের সময়সমূহ অধ্যায়",
  "The Book of the Adhan (The Call to Prayer)": "আজান অধ্যায়",
  "The Book of the Masjids": "মসজিদসমূহ অধ্যায়",
  "The Book of the Qiblah": "কিবলা অধ্যায়",
  "The Book of Leading the Prayer (Al-Imamah)": "ইমামতি অধ্যায়",
  "The Book of the Commencement of the Prayer": "নামাজ শুরু করা অধ্যায়",
  "The Book of The At-Tatbiq (Clasping One's Hands Together)": "আত-তাতবিক (রুকুতে হাত জোড়া করা) অধ্যায়",
  "The Book of Forgetfulness (In Prayer)": "সাহু সিজদা (নামাজে ভুল) অধ্যায়",
  "The Book of Jumu'ah (Friday Prayer)": "জুমুআ অধ্যায়",
  "The Book of Shortening the Prayer When Traveling": "সফরে কসর নামাজ অধ্যায়",
  "The Book of Praying for Rain (Al-Istisqa')": "ইস্তিসকা (বৃষ্টির জন্য দোয়া) অধ্যায়",
  "The Book of the Fear Prayer": "ভীভিকালীন নামাজ অধ্যায়",
  "The Book of the Prayer for the Two 'Eids": "দুই ঈদের নামাজ অধ্যায়",
  "The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day": "কিয়ামুল লাইল (তাহাজ্জুদ) ও নফল নামাজ অধ্যায়",
  "The Book of Funerals": "জানাজা অধ্যায়",
  "The Book of Zakah": "যাকাত অধ্যায়",
  "The Book of Horses, Races and Shooting": "ঘোড়া, দৌড় এবং তীরন্দাজি অধ্যায়",
  "The Book of Endowments": "ওয়াকফ (দান) অধ্যায়",
  "The Book of Presents": "উপহার অধ্যায়",
  "The Book of ar-Ruqba": "রুকবা (শর্তযুক্ত দান) অধ্যায়",
  "The Book of 'Umra": "ওমরাহ (দান) অধ্যায়",
  "The Book of the Kind Treatment of Women": "নারীদের সাথে সদাচরণ অধ্যায়",
  "The Book of Fighting [The Prohibition of Bloodshed]": "যুদ্ধ ও রক্তপাত নিষিদ্ধকরণ অধ্যায়",
  "The Book of Distribution of Al-Fay'": "ফায় (বিনা যুদ্ধে লব্ধ সম্পদ) বণ্টন অধ্যায়",
  "The Book of al-Bay'ah": "বায়াত (আনুগত্যের শপথ) অধ্যায়",
  "The Book of al-'Aqiqah": "আকিকা অধ্যায়",
  "The Book of al-Fara' and al-'Atirah": "ফার'আ এবং আতিরাহ অধ্যায়",
  "The Book of Hunting and Slaughtering": "শিকার ও জবাই অধ্যায়",
  "The Book of ad-Dahaya (Sacrifices)": "কুরবানী অধ্যায়",
  "The Book of Financial Transactions": "আর্থিক লেনদেন অধ্যায়",
  "The Book of Oaths (qasamah), Retaliation and Blood Money": "কসম, কিসাস ও দিয়াত অধ্যায়",
  "The Book of Cutting off the Hand of the Thief": "চোরের হাত কাটা অধ্যায়",
  "The Book Of Faith and its Signs": "ঈমান ও তার নিদর্শনসমূহ অধ্যায়",
  "The Book of Adornment": "সাজসজ্জা অধ্যায়",
  "The Book of the Etiquette of Judges": "বিচারকদের আদব-কায়দা অধ্যায়",
  "The Book of Seeking Refuge with Allah": "আল্লাহর কাছে আশ্রয় প্রার্থনা অধ্যায়",

  // Sunan Ibn Majah & Others
  "The Book of the Sunnah": "সুন্নাহ অধ্যায়",
  "The Book of Purification and its Sunnah": "পবিত্রতা ও তার সুন্নাহ অধ্যায়",
  "The Book of the Prayer": "সালাত (নামাজ) অধ্যায়",
  "The Book of the Adhan and the Sunnah Regarding It": "আজান ও তার সুন্নাহ অধ্যায়",
  "The Book On The Mosques And The Congregations": "মসজিদ ও জামাত অধ্যায়",
  "Establishing the Prayer and the Sunnah Regarding Them": "সালাত কায়েম ও তার সুন্নাহ অধ্যায়",
  "Chapters Regarding Funerals": "জানাজা অধ্যায়",
  "The Chapters Regarding Zakat": "যাকাত অধ্যায়",
  "The Chapters on Marriage": "বিবাহ অধ্যায়",
  "The Chapters on Divorce": "তালাক অধ্যায়",
  "The Chapters on Expiation": "কাফফারা অধ্যায়",
  "The Chapters on Business Transactions": "ব্যবসায়িক লেনদেন অধ্যায়",
  "The Chapters on Rulings": "বিচার ফয়সালা ও আহকাম অধ্যায়",
  "The Chapters on Gifts": "উপহার বা হিবাহ অধ্যায়",
  "The Chapters on Charity": "দান-সদকা অধ্যায়",
  "The Chapters on Pawning": "বন্ধক রাখা অধ্যায়",
  "The Chapters on Pre-emption": "শুফ'আ (অগ্রক্রয়াধিকার) অধ্যায়",
  "The Chapters on Lost Property": "হারানো বস্তু (লুকাতা) অধ্যায়",
  "The Chapters on Manumission (of Slaves)": "দাস মুক্তি অধ্যায়",
  "The Chapters on Legal Punishments": "হুদুদ (দণ্ডবিধি) অধ্যায়",
  "The Chapters on Blood Money": "রক্তপণ (দিয়াত) অধ্যায়",
  "The Chapters on Wills": "ওসিয়ত অধ্যায়",
  "Chapters on Shares of Inheritance": "উত্তরাধিকার বন্টন (ফারায়েজ) অধ্যায়",
  "The Chapters on Jihad": "জিহাদ অধ্যায়",
  "Chapters on Hajj Rituals": "হজের বিধি-বিধান অধ্যায়",
  "Chapters on Sacrifices": "কুরবানী অধ্যায়",
  "Chapters on Slaughtering": "জবাই করা অধ্যায়",
  "Chapters on Hunting": "শিকার অধ্যায়",
  "Chapters on Food": "খাবার অধ্যায়",
  "Chapters on Drinks": "পানীয় অধ্যায়",
  "Chapters on Dress": "পোশাক-পরিচ্ছদ অধ্যায়",
  "Etiquette": "আদব-কায়দা বা শিষ্টাচার",
  "Supplication": "দোয়া",
  "Tribulations": "ফিতনা",
  "Zuhd": "জুহুদ (দুনিয়াবিমুখতা)",

  // Muwatta Malik specific additions
  "The Times of Prayer": "নামাজের সময়সমূহ অধ্যায়",
  "Purity": "পবিত্রতা অধ্যায়",
  "Prayer": "সালাত (নামাজ) অধ্যায়",
  "Jumu'a": "জুমুআ অধ্যায়",
  "Prayer in Ramadan": "রমজানের নামাজ অধ্যায়",
  "Tahajjud": "তাহাজ্জুদ অধ্যায়",
  "Prayer in Congregation": "জামাতে নামাজ অধ্যায়",
  "Shortening the Prayer": "কসর নামাজ অধ্যায়",
  "The Two 'Ids": "দুই ঈদ অধ্যায়",
  "The Fear Prayer": "ভীভিকালীন নামাজ অধ্যায়",
  "The Eclipse Prayer": "সূর্যগ্রহণ ও চন্দ্রগ্রহণ নামাজ অধ্যায়",
  "Asking for Rain": "বৃষ্টির জন্য দোয়া (ইস্তিসকা) অধ্যায়",
  "The Qibla": "কিবলা অধ্যায়",
  "The Qur'an": "কুরআন অধ্যায়",
  "Burials": "দাফন অধ্যায়",
  "I'tikaf in Ramadan": "রমজানে ইতিকাফ অধ্যায়",
  "Jihad": "জিহাদ অধ্যায়",
  "Vows and Oaths": "মান্নত ও কসম অধ্যায়",
  "Sacrificial Animals": "কুরবানীর পশু অধ্যায়",
  "Slaughtering Animals": "পশু জবাই অধ্যায়",
  "Game": "শিকার অধ্যায়",
  "The 'Aqiqa": "আকিকা অধ্যায়",
  "Fara'id": "ফারায়েজ (উত্তরাধিকার) অধ্যায়",
  "Suckling": "দুগ্ধপান অধ্যায়",
  "Business Transactions": "ব্যবসায়িক লেনদেন অধ্যায়",
  "Qirad": "কিরাদ (মুদারাবা) অধ্যায়",
  "Sharecropping": "বর্গাচাষ অধ্যায়",
  "Renting Land": "জমি ভাড়া দেয়া অধ্যায়",
  "Pre-emption in Property": "সম্পত্তিতে শুফ'আ অধ্যায়",
  "Judgements": "বিচার ফয়সালা অধ্যায়",
  "Wills and Testaments": "ওসিয়ত অধ্যায়",
  "Setting Free and Wala'": "দাস মুক্তি ও ওয়ালা অধ্যায়",
  "The Mukatab": "মুকাতাব (চুক্তিবদ্ধ দাস) অধ্যায়",
  "The Mudabbar": "মুদাব্বার (মনিবের মৃত্যুর পর মুক্ত দাস) অধ্যায়",
  "Hudud": "হুদুদ (দণ্ডবিধি) অধ্যায়",
  "Blood-Money": "রক্তপণ (দিয়াত) অধ্যায়",
  "The Oath of Qasama": "কাসামাহ (শপথ) অধ্যায়",
  "Madina": "মদিনা অধ্যায়",
  "The Decree": "তাকদীর অধ্যায়",
  "Good Character": "সচ্চরিত্র অধ্যায়",
  "The Description of the Prophet, may Allah Bless Him and Grant Him Peace": "নবী (সাঃ) এর বর্ণনা অধ্যায়",
  "The Evil Eye": "বদ নজর অধ্যায়",
  "Hair": "চুল অধ্যায়",
  "Visions": "স্বপ্ন অধ্যায়",
  "Greetings": "সালাম ও অভিবাদন অধ্যায়",
  "General Subjects": "বিবিধ বিষয় অধ্যায়",
  "The Oath of Allegiance": "বায়াত অধ্যায়",
  "Speech": "কথাবার্তা অধ্যায়",
  "Jahannam": "জাহান্নাম অধ্যায়",
  "Sadaqa": "সদকা অধ্যায়",
  "The Supplication of the Unjustly Wronged": "মজলুমের দোয়া অধ্যায়",
  "The Names of the Prophet, may Allah Bless Him and Grant Him Peace": "নবী (সাঃ) এর নামসমূহ অধ্যায়",

  // Common variations
  "The Book of Faith": "ঈমান অধ্যায়",
  "The Book of Purification": "পবিত্রতা অধ্যায়",
  "The Book of Menstruation": "ঋতুস্রাব অধ্যায়",
  "The Book of Prayers": "সালাত অধ্যায়",
  "The Book of Zakat": "যাকাত অধ্যায়",
  "The Book of Fasting": "সাওম অধ্যায়",
  "The Book of Pilgrimage": "হজ অধ্যায়",
  "The Book of Marriage": "বিবাহ অধ্যায়",
  "The Book of Divorce": "তালাক অধ্যায়",
  "The Book of Jihad": "জিহাদ অধ্যায়",
  "The Book of Business Transactions": "ক্রয়-বিক্রয় অধ্যায়",
  "The Book of Wills": "ওসিয়ত অধ্যায়",
  "The Book of Vows and Oaths": "কসম ও মান্নত অধ্যায়",
  "The Book of Food": "খাবার অধ্যায়",
  "The Book of Drinks": "পানীয় অধ্যায়",
  "The Book of Clothing and Decoration": "পোশাক ও সাজসজ্জা অধ্যায়",
  "The Book of Manners and Etiquette": "আদব-কায়দা অধ্যায়",
  "The Book of Greetings": "সালাম ও অভিবাদন অধ্যায়",
  "The Book of Poetry": "কবিতা অধ্যায়",
  "The Book of Dreams": "স্বপ্ন অধ্যায়",
  "The Book of Virtues": "ফজিলত অধ্যায়",
  "The Book of Merits": "মর্যাদা অধ্যায়",
  "The Book of Tribulations and Portents of the Last Hour": "ফিতনা ও কেয়ামতের আলামত",
  "The Book of Zuhd and Softening of Hearts": "জুহুদ ও রিকাক",
  "Introduction": "ভূমিকা",
  "The Book on Purification": "শুদ্ধিকরণ সংক্রান্ত বই",
  "Forty Hadith Qudsi": "চল্লিশটি হাদিসে কুদসী",
  "Zakat": "যাকাত",
  "Marriage": "বিবাহ",
  "The Book Concerning the Use of Correct Words": "সঠিক শব্দের ব্যবহার সম্পর্কিত বই",
  "Forty Hadith of an-Nawawi": "আন-নববীর চল্লিশটি হাদিস",
  "Forty Hadith of Shah Waliullah Dehlawi": "শাহ ওয়ালীউল্লাহ দেহলভীর চল্লিশটি হাদীস"
};
